-- AlterTable
ALTER TABLE "Todo" ALTER COLUMN "updateAt" SET DATA TYPE TEXT,
ALTER COLUMN "createdAt" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "TodoList" ALTER COLUMN "updateAt" SET DATA TYPE TEXT,
ALTER COLUMN "createdAt" SET DATA TYPE TEXT;
