-- AlterTable
ALTER TABLE "Todo" ALTER COLUMN "completed" SET DEFAULT false,
ALTER COLUMN "updateAt" SET DATA TYPE BIGINT,
ALTER COLUMN "createdAt" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "TodoList" ALTER COLUMN "updateAt" SET DATA TYPE BIGINT,
ALTER COLUMN "createdAt" SET DATA TYPE BIGINT;
